## Nathaniel Lim
## CS432 - Spring 2011
## Assignment 2: 3/2/2011
## A (Really) Simple Make File
## Make with:  'make wsh'
## Clean with  'make clean'
## compile freq
freq :
	gcc -o freq freq.c ts.h ts.c hash.h hash.c

## Remove wsh
clean :
	rm freq
