## Nathaniel Lim
## CS432 - Spring 2011
## Assignment 2: 3/2/2011
## A (Really) Simple Make File
## Make with:  'make wsh'
## Clean with  'make 
PROG = wsh
SRC = wsh.c

## compile wsh
$(PROG):
	gcc -o $(PROG) $(SRC)

## Remove wsh
clean :
	rm $(PROG)

